name: Test Pytest
on: [push, pull_request]
 
permissions:
  contents: read
 
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Build image
        run: |
          docker-compose -f ./docker-compose.yml build
      - name: Run Tests
        run: |          
          docker-compose -f ./docker-compose.yml run test
      - name: Stop Docker compose
        run: |
          docker-compose -f ./docker-compose.yml down
